I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 55, in script
    python:
  File "game/script.rpy", line 66, in <module>
    response = requests.post('http://localhost:8000/submit_score/', data=json.dumps(data), headers=headers)
ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /submit_score/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000005bc0460>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 55, in script
    python:
  File "G:\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "G:\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 66, in <module>
    response = requests.post('http://localhost:8000/submit_score/', data=json.dumps(data), headers=headers)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/requests/api.py", line 116, in post
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/requests/api.py", line 60, in request
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/requests/sessions.py", line 524, in request
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/requests/sessions.py", line 637, in send
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /submit_score/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000000005bc0460>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
striped_template 1.0
Sat Mar 25 20:19:27 2023
